# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.


from odoo import fields, models


class ProductTemplate(models.Model):
    _inherit = "product.template"

    codigo_alternativo_1 = fields.Many2one('product.template', 'Product')
    #codigo_alternativo_1 = fields.Char(string="Código alternativo 1:", required=False, )
    codigo_alternativo_2 = fields.Many2one('product.template', 'Product')

    fabricante = fields.Selection(string="Fabricante de máquina:", selection=[
                                                   ('dka', 'DURKOP Adler'),
                                                   ('af', 'Alfa'),
                                                   ('altin', 'ALTIN'),
                                                   ('ANKPH', 'Anker-Phoenix'),
                                                   ('ATTFOR', 'Attilio Forte'),
                                                   ('baoma', 'BAOMA'),
                                                   ('BRTTO', 'Baratto'),
                                                   ('BRDAN', 'Barudan'),
                                                   ('beaver', 'BEAVER'),
                                                   ('bernina', 'BERNINA'),
                                                   ('bonis', 'BONIS'),
                                                   ('brother', 'BROTHER'),
                                                   ('bc', 'Blindstitch -- Columbia'),
                                                   ('bm', 'Blindstitch -- Miscellaneous'),
                                                   ('USBLD', 'Blindstitch -- U.S.'),
                                                   ('bha', 'Brother Home Appliances'),
                                                   ('cra', 'CRA'),
                                                   ('chandler', 'CHANDLER'),
                                                   ('ciucani', 'CIUCANI'),
                                                   ('clinton', 'CLINTON'),
                                                   ('colli', 'COLLI'),
                                                   ('compo', 'COMPO'),
                                                   ('consew', 'CONSEW'),
                                                   ('CRNLY', 'Cornelly'),
                                                   ('dexter', 'DEXTER'),
                                                   ('diamant', 'DIAMANT FR'),
                                                   ('durkopp', 'DURKOPP'),
                                                   ('eastman', 'Eastman'),
                                                   ('eldridge', 'Eldridge'),
                                                   ('eltac', 'ELTAC'),
                                                   ('e-sew', 'E-SEW'),
                                                   ('fischbein', 'Fischbein'),
                                                   ('fomax', 'FOMAX'),
                                                   ('fortuna', 'FORTUNA'),
                                                   ('free', 'Free & New Home'),
                                                   ('fuchaobei', 'Fuchaobei'),
                                                   ('global', 'GLOBAL'),
                                                   ('gross', 'Gross-Marco'),
                                                   ('gury', 'GURY'),
                                                   ('garudan', 'Garudan'),
                                                   ('gemsy', 'GEMSY'),
                                                   ('happy', 'Happy'),
                                                   ('hashima', 'Hashima'),
                                                   ('highlead', 'HighLead'),
                                                   ('hoog', 'HOOG'),
                                                   ('ideal', 'IDEAL'),
                                                   ('ivomaq', 'IVOMAQ'),
                                                   ('jack', 'JACK'),
                                                   ('janome', 'Janome'),
                                                   ('juki', 'JUKI'),
                                                   ('kansai special', 'KANSAI SPECIAL'),
                                                   ('kingtex', 'Kingtex'),
                                                   ('km machines', 'KM Machines'),
                                                   ('landis', 'LANDIS'),
                                                   ('lijia', 'LIJIA'),
                                                   ('maier', 'MAIER'),
                                                   ('maimin', 'MAIMIN'),
                                                   ('man-sew', 'Man-Sew'),
                                                   ('mauser', 'MAUSER'),
                                                   ('meca', 'MECA'),
                                                   ('meistergram', 'Meistergram'),
                                                   ('melco', 'MELCO'),
                                                   ('merrow', 'MERROW'),
                                                   ('metropolitan', 'Metropolitan'),
                                                   ('mitsubishi', 'Mitsubishi'),
                                                   ('machine meto', 'Machine Meto'),
                                                   ('nakajima', 'Nakajima'),
                                                   ('nechi', 'NECHI'),
                                                   ('newlong', 'NEWLONG'),
                                                   ('omac', 'OMAC'),
                                                   ('peerless', 'Peerless'),
                                                   ('pegasus', 'PEGASUS'),
                                                   ('pfaff', 'PFAFF'),
                                                   ('porter', 'PORTER'),
                                                   ('reece', 'REECE'),
                                                   ('refrey', 'REFREY'),
                                                   ('renown', 'RENOWN'),
                                                   ('rimold', 'Rimold'),
                                                   ('rotozip', 'ROTO ZIP'),
                                                   ('resta', 'RESTA'),
                                                   ('seiko', 'SEIKO'),
                                                   ('singer', 'SINGER'),
                                                   ('sister', 'SISTER'),
                                                   ('siruba', 'SIRUBA'),
                                                   ('sotco', 'SOTCO'),
                                                   ('shing ling', 'SHING LING'),
                                                   ('sunstar', 'SUNSTAR'),
                                                   ('s/m', 'S/M'),
                                                   ('tabony', 'TABONY'),
                                                   ('tajma', 'TAJMA'),
                                                   ('titan', 'TITAN'),
                                                   ('toyota', 'TOYOTA'),
                                                   ('treauser', 'TREASURE'),
                                                   ('typical', 'Typical'),
                                                   ('unicorn', 'UNICORN'),
                                                   ('union special', 'Union Special'),
                                                   ('united shoe machine', 'United Shoe Machine'),
                                                   ('vibemac', 'Vibemac'),
                                                   ('white & franklin', 'White & Franklin'),
                                                   ('willcox & gibbs', 'Willcox & Gibbs'),
                                                   ('wolf', 'WOLF'),
                                                   ('yakumo', 'YAKUMO'),
                                                   ('yamato', 'YAMATO'),
                                                   ('yulun', 'YULUN'),
                                                   ('w&w', 'W&W'),
                                                   ('zoje', 'ZOJE'),
                                                   ], required=False, )

    marca_sw = fields.Selection(string="Marca:", selection=[  
                                                    ('JK-SHIRLEYIIE'),
                                                    ('9817H-D4'),
                                                    ('ZJ9703AR-D4J/01'),
                                                    ('AZ8003-04DA'),
                                                    ('M700'),
                                                    ('S/M'),
                                                    ('SC9214'),
                                                    ('SR747-514M2-24'),
                                                    ('ZJ747A-514M2-24'),
                                                    ('DB2-B737-413'),
                                                    ('DB2-B737-415S'),
                                                    ('DD7100-903'),
                                                    ('JK-8991DYN-4SS'),
                                                    ('L8L8F-DM101'),
                                                    ('L8L8F-H101'),
                                                    ('L8L8F-M101'),
                                                    ('L8L8F-M111'),
                                                    ('LB9000E'),
                                                    ('VE271-156S-2-K4N-8F/UT-A34F'),
                                                    ('VG2700-156M'),
                                                    ('W1600'),
                                                    ('W600'),
                                                    ('KM-250A-7S'),
                                                    ('D7100-903'),
                                                    ('DB2-B797-415S'),
                                                    ('S-7200A-433'),
                                                    ('DB2-B797-413'),
                                                    ('AZ8020G-Y5DF'),
                                                    ('AZF8003G-04DF'),
                                                    ('CZ6120-Y5DF'),
                                                    ('L8200-04M2-24'),
                                                    ('EX5204-82'),
                                                    ('SR737-504M2-04'),
                                                    ('ZJ747A-514M5-23BK'),
                                                    ('L6200-01MS-6.0-D'),
                                                    ('VG-888S-356/AST'),
                                                    ('VG-888S'),
                                                    ('LK-1900HS'),
                                                    ('JK-T1900BSK'),
                                                    ('LBH-780'),
                                                    ('514M2-24'),
                                                    ('747F-514M2-24'),
                                                    ('AZ8003H-04DA'),
                                                    ('CZ6125-Y5DF'),
                                                    ('C5-5-03/233/KH/Z'),
                                                    ('SR737-514M2-24'),
                                                    ('EX5214-M03C3'),
                                                    ('L8100-04M2-24'),
                                                    ('L8100-04M2-25'),
                                                    ('SR747-514M2-25'),
                                                    ('VC2700-156L'),
                                                    ('VC713-156L-I'),
                                                    ('VG2700-154M'),
                                                    ('SL-703-452-G3'),
                                                    ('SL-703-G3-460'),
                                                    ('LK-1900AHS'),
                                                    ('AZ 8412-03DA'),
                                                    ('CZ 6120Y5DF'),
                                                    ('VC2711-156L-2'),
                                                    ('VC2713-156L-1'),
                                                    ('AZ8420SD-Y5DF-70/K2'),
                                                    ('EX5104'),
                                                    ('747FS-514M2-24'),
                                                    ('ZJ9703AR-DAJ/01'),
                                                    ('ES-GA'),
                                                    ('L8200-04DM2-24-7/P'),
                                                    ('L2100-04DM2-24-7/P/C'),
                                                    ('VE2700'),
                                                    ('DLN-5410'),
                                                    ('LK-1803'),
                                                    ('DLN-5410-6'),
                                                    ('DL-5410-6'),
                                                    ('FX4409P'),
                                                    ('MO-2516N'),
                                                    ('HALBH-783'),
                                                    ('L818-M101'),
                                                    ('MH-481'),
                                                    ('LBH-1700'),
                                                    ('LBH-782'),

                                                            ], required=False, )







