# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.


from odoo import fields, models


class ProductTemplate(models.Model):
    _inherit = "product.template"

    codigo_alternativo_1 = fields.Many2one('product.template', 'Product')
    #codigo_alternativo_1 = fields.Char(string="Código alternativo 1:", required=False, )
    codigo_alternativo_2 = fields.Many2one('product.template', 'Product')

    fabricante = fields.Selection(string="Fabricante de máquina:", selection=[
                                                   ('dka', 'DURKOP Adler'),
                                                   ('af', 'Alfa'),
                                                   ('altin', 'ALTIN'),
                                                   ('ANKPH', 'Anker-Phoenix'),
                                                   ('ATTFOR', 'Attilio Forte'),
                                                   ('baoma', 'BAOMA'),
                                                   ('BRTTO', 'Baratto'),
                                                   ('BRDAN', 'Barudan'),
                                                   ('beaver', 'BEAVER'),
                                                   ('bernina', 'BERNINA'),
                                                   ('bonis', 'BONIS'),
                                                   ('brother', 'BROTHER'),
                                                   ('bc', 'Blindstitch -- Columbia'),
                                                   ('bm', 'Blindstitch -- Miscellaneous'),
                                                   ('USBLD', 'Blindstitch -- U.S.'),
                                                   ('bha', 'Brother Home Appliances'),
                                                   ('cra', 'CRA'),
                                                   ('chandler', 'CHANDLER'),
                                                   ('ciucani', 'CIUCANI'),
                                                   ('clinton', 'CLINTON'),
                                                   ('colli', 'COLLI'),
                                                   ('compo', 'COMPO'),
                                                   ('consew', 'CONSEW'),
                                                   ('CRNLY', 'Cornelly'),
                                                   ('dexter', 'DEXTER'),
                                                   ('diamant', 'DIAMANT FR'),
                                                   ('durkopp', 'DURKOPP'),
                                                   ('eastman', 'Eastman'),
                                                   ('eldridge', 'Eldridge'),
                                                   ('eltac', 'ELTAC'),
                                                   ('e-sew', 'E-SEW'),
                                                   ('fischbein', 'Fischbein'),
                                                   ('fomax', 'FOMAX'),
                                                   ('fortuna', 'FORTUNA'),
                                                   ('free', 'Free & New Home'),
                                                   ('fuchaobei', 'Fuchaobei'),
                                                   ('global', 'GLOBAL'),
                                                   ('gross', 'Gross-Marco'),
                                                   ('gury', 'GURY'),
                                                   ('garudan', 'Garudan'),
                                                   ('gemsy', 'GEMSY'),
                                                   ('happy', 'Happy'),
                                                   ('hashima', 'Hashima'),
                                                   ('highlead', 'HighLead'),
                                                   ('hoog', 'HOOG'),
                                                   ('ideal', 'IDEAL'),
                                                   ('ivomaq', 'IVOMAQ'),
                                                   ('jack', 'JACK'),
                                                   ('janome', 'Janome'),
                                                   ('juki', 'JUKI'),
                                                   ('kansai special', 'KANSAI SPECIAL'),
                                                   ('kingtex', 'Kingtex'),
                                                   ('km machines', 'KM Machines'),
                                                   ('landis', 'LANDIS'),
                                                   ('lijia', 'LIJIA'),
                                                   ('maier', 'MAIER'),
                                                   ('maimin', 'MAIMIN'),
                                                   ('man-sew', 'Man-Sew'),
                                                   ('mauser', 'MAUSER'),
                                                   ('meca', 'MECA'),
                                                   ('meistergram', 'Meistergram'),
                                                   ('melco', 'MELCO'),
                                                   ('merrow', 'MERROW'),
                                                   ('metropolitan', 'Metropolitan'),
                                                   ('mitsubishi', 'Mitsubishi'),
                                                   ('machine meto', 'Machine Meto'),
                                                   ('nakajima', 'Nakajima'),
                                                   ('nechi', 'NECHI'),
                                                   ('newlong', 'NEWLONG'),
                                                   ('omac', 'OMAC'),
                                                   ('peerless', 'Peerless'),
                                                   ('pegasus', 'PEGASUS'),
                                                   ('pfaff', 'PFAFF'),
                                                   ('porter', 'PORTER'),
                                                   ('reece', 'REECE'),
                                                   ('refrey', 'REFREY'),
                                                   ('renown', 'RENOWN'),
                                                   ('rimold', 'Rimold'),
                                                   ('rotozip', 'ROTO ZIP'),
                                                   ('resta', 'RESTA'),
                                                   ('seiko', 'SEIKO'),
                                                   ('singer', 'SINGER'),
                                                   ('sister', 'SISTER'),
                                                   ('siruba', 'SIRUBA'),
                                                   ('sotco', 'SOTCO'),
                                                   ('shing ling', 'SHING LING'),
                                                   ('sunstar', 'SUNSTAR'),
                                                   ('s/m', 'S/M'),
                                                   ('tabony', 'TABONY'),
                                                   ('tajma', 'TAJMA'),
                                                   ('titan', 'TITAN'),
                                                   ('toyota', 'TOYOTA'),
                                                   ('treauser', 'TREASURE'),
                                                   ('typical', 'Typical'),
                                                   ('unicorn', 'UNICORN'),
                                                   ('union special', 'Union Special'),
                                                   ('united shoe machine', 'United Shoe Machine'),
                                                   ('vibemac', 'Vibemac'),
                                                   ('white & franklin', 'White & Franklin'),
                                                   ('willcox & gibbs', 'Willcox & Gibbs'),
                                                   ('wolf', 'WOLF'),
                                                   ('yakumo', 'YAKUMO'),
                                                   ('yamato', 'YAMATO'),
                                                   ('yulun', 'YULUN'),
                                                   ('w&w', 'W&W'),
                                                   ('zoje', 'ZOJE'),
                                                   ], required=False, )

    marca_sw = fields.Selection(string="Marca:", selection=[  
                                                    ('jk-shirleyiie','JK-SHIRLEYIIE'),
                                                    ('9817h-d4','9817H-D4'),
                                                    ('zj9703ar-d4j/01','ZJ9703AR-D4J/01'),
                                                    ('az8003-04da','AZ8003-04DA'),
                                                    ('m700','M700'),
                                                    ('s/m','S/M'),
                                                    ('sc9214','SC9214'),
                                                    ('sr747-514m2-24','SR747-514M2-24'),
                                                    ('zj747a-514m2-24','ZJ747A-514M2-24'),
                                                    ('db2-b737-413','DB2-B737-413'),
                                                    ('db2-b737-415s','DB2-B737-415S'),
                                                    ('dd7100-903','DD7100-903'),
                                                    ('jk-8991dyn-4ss','JK-8991DYN-4SS'),
                                                    ('l8l8f-dm101','L8L8F-DM101'),
                                                    ('l8l8f-h101','L8L8F-H101'),
                                                    ('l8l8f-m101','L8L8F-M101'),
                                                    ('l8l8f-m111','L8L8F-M111'),
                                                    ('lb9000e','LB9000E'),
                                                    ('ve271-156s-2-k4n-8f/ut-a34f','VE271-156S-2-K4N-8F/UT-A34F'),
                                                    ('vg2700-156m','VG2700-156M'),
                                                    ('w1600','W1600'),
                                                    ('w600','W600'),
                                                    ('km-250a-7s','KM-250A-7S'),
                                                    ('d7100-903','D7100-903'),
                                                    ('db2-b797-415s','DB2-B797-415S'),
                                                    ('s-7200a-433','S-7200A-433'),
                                                    ('db2-b797-413','DB2-B797-413'),
                                                    ('az8020g-y5df','AZ8020G-Y5DF'),
                                                    ('azf8003g-04df','AZF8003G-04DF'),
                                                    ('cz6120-y5df','CZ6120-Y5DF'),
                                                    ('l8200-04m2-24'),'L8200-04M2-24'),
                                                    ('ex5204-82','EX5204-82'),
                                                    ('sr737-504m2-04','SR737-504M2-04'),
                                                    ('zj747a-514m5-23bk','ZJ747A-514M5-23BK'),
                                                    ('l6200-01ms-6.0-d','L6200-01MS-6.0-D'),
                                                    ('vg-888s-356/ast','VG-888S-356/AST'),
                                                    ('vg-888s','VG-888S'),
                                                    ('lk-1900hs','LK-1900HS'),
                                                    ('jk-t1900bsk','JK-T1900BSK'),
                                                    ('lbh-780','LBH-780'),
                                                    ('514m2-24','514M2-24'),
                                                    ('747f-514m2-24','747F-514M2-24'),
                                                    ('az8003h-04da','AZ8003H-04DA'),
                                                    ('cz6125-y5df','CZ6125-Y5DF'),
                                                    ('c5-5-03/233/kh/z','C5-5-03/233/KH/Z'),
                                                    ('sr737-514m2-24','SR737-514M2-24'),
                                                    ('ex5214-m03c3','EX5214-M03C3'),
                                                    ('l8100-04m2-24','L8100-04M2-24'),
                                                    ('l8100-04m2-25','L8100-04M2-25'),
                                                    ('sr747-514m2-25','SR747-514M2-25'),
                                                    ('vc2700-156l','VC2700-156L'),
                                                    ('vc713-156l-i','VC713-156L-I'),
                                                    ('vg2700-154m','VG2700-154M'),
                                                    ('sl-703-452-g3','SL-703-452-G3'),
                                                    ('sl-703-g3-460','SL-703-G3-460'),
                                                    ('lk-1900ahs','LK-1900AHS'),
                                                    ('az 8412-03da','AZ 8412-03DA'),
                                                    ('cz 6120y5df','CZ 6120Y5DF'),
                                                    ('vc2711-156l-2','VC2711-156L-2'),
                                                    ('vc2713-156l-1','VC2713-156L-1'),
                                                    ('az8420sd-y5df-70/k2','AZ8420SD-Y5DF-70/K2'),
                                                    ('ex5104','EX5104'),
                                                    ('747fs-514m2-24','747FS-514M2-24'),
                                                    ('zj9703ar-daj/01','ZJ9703AR-DAJ/01'),
                                                    ('es-ga','ES-GA'),
                                                    ('l8200-04dm2-24-7/p','L8200-04DM2-24-7/P'),
                                                    ('l2100-04dm2-24-7/p/c','L2100-04DM2-24-7/P/C'),
                                                    ('ve2700','VE2700'),
                                                    ('dln-5410','DLN-5410'),
                                                    ('lk-1803','LK-1803'),
                                                    ('dln-5410-6','DLN-5410-6'),
                                                    ('dl-5410-6','DL-5410-6'),
                                                    ('fx4409p','FX4409P'),
                                                    ('mo-2516n','MO-2516N'),
                                                    ('halbh-783','HALBH-783'),
                                                    ('l818-m101','L818-M101'),
                                                    ('mh-481','MH-481'),
                                                    ('lbh-1700','LBH-1700'),
                                                    ('lbh-782','LBH-782'),

                                                            ], required=False, )







